[package]
name = "portal-verkle-trie"
version = "0.1.0"
edition = "2021"
description = "Implementation of the Portal Network version of the Verkle trie."
license = "MIT"
readme = "README.md"
keywords = ["ethereum", "portal-network", "verkle"]
